### ISSUE TITLE
a few crashes

### ISSUE THREAD

**Issue by adid4s** [radgeRayden/future-mari0#4]
After booting up the game it immediately crashed and froze just before the "stabyourself" animation, had to reboot my pi, I tried again and it started just fine, I configured my xbox wireless controller, and gameplay went smooth I played single for about 25 minutes, I noticed a little bit of slowdown but it was still playable and enjoyable, I'm sure it was because I'm playing on a pi, also tried multiplayer for a few minutes and that worked fine as well with a second controller, for some reason when I was done I hut escape and then selected quit to desktop and then the game crashed once again, and wouldn't start up anymore after that, the error message said something about a missing music file I believe, mushroom something or another, since it wouldn't boot up again I deleted the game and reinstalled and it worked like a charm again, after that quitting to menu, and then Hitting escape was the best way to exit. I'm sorry if these are not issues, maybe it's because I'm on raspberry pi, but I just wanted to  leave feedback for you, but game is great I tried normal mario levels and portal ones as well

**Comment by radgeRayden** [comment]
Just a reminder that it's not my game, so if you like what you see go take a look at other stuff from http://stabyourself.net.

I'm not sure if those are really bugs but I'm not closing the issue because they might be. If you keep encountering the same errors please take note of the error messages and post here so I can verify what's going on.

**Comment by adid4s** [comment]
I booted up the game several times since the first issue, and haven't encountered any crashes
